ALTER TABLE audit_logs ALTER COLUMN actor_id DROP NOT NULL;
ALTER TABLE audit_logs ALTER COLUMN actor_name DROP NOT NULL;
ALTER TABLE audit_logs ALTER COLUMN description DROP NOT NULL;
ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE salary_slips ADD COLUMN IF NOT EXISTS status TEXT;
